### ISSUE TITLE
Bug - Application de dommages à la cible par un joueur

### ISSUE THREAD

**Issue by WarAmara** [ZigmundKreud/bol#11]
Si un joueur cible et réussi une attaque sur un PNJ, il peut lancer les dommages. Il peut ensuite cliquer sur "Appliquer les dommages à la cible", mais rien ne se passe.
Les PVs du PNJ ne sont pas modifiés.

Si on teste la même chose en mode "Assistant GM" ou "GM". On arrive sur l'option d'encaissement des dommages (avec ou sans protection de l'armure) et ensuite les dommages sont éventuellement appliqués avec mise à jour de la barre du Token.

**Comment by LeRatierBretonnien** [comment]
Correction dans la gestion des échanges de combats
