### ISSUE TITLE
Looking to help/do with English Translation

### ISSUE THREAD

**Issue by discuit** [ZigmundKreud/bol#12]
Hi there. I have gone through the en.json and done my best to edit this to make it usable in English but the actual character sheet still maintains a lot of the French terminology. We'd really love to use this system, so I was wondering If anyone would be prepared to help me with this? Well, talk me through what I'm missing anyway. Thanks!

**Comment by LeRatierBretonnien** [comment]
The system is derivated from the Barbarians of Lemuria french game, with some modifications from the original BoL. So some stuff will probably looks strange from the US side if you don't have the French updated rules (and they are not translated). 
In addition, many texts are hardcoded in the system AND you will have also to translate all the compendiums with the babele module.
The best solution is to find people on the Foundry US Discord to help you on this.

**Comment by LeRatierBretonnien** [comment]
You need to edit the `lang/en.json` and translate all the french parts. When done, push it as a PR.

**Comment by discuit** [comment]
I had just completed editing the json and testing it and noticed it has now already been done. Thank you to whomever did that. I take it the Nom, Defensee, Totale, and the description Tab cannot be edited as they are part of the actual sheet graphic?

**Comment by LeRatierBretonnien** [comment]
New release pushed, with missing translation keys (version 1.3.13)
