### ISSUE TITLE
Are there bigger differences to the german (or english) version?

### ISSUE THREAD

**Issue by gsterling** [ZigmundKreud/bol#16]
The french version you linked looks like the same version sold in germany, but in french. Do you know if there are bigger differences, that prevents me from refenrencing the german adaption in the translation? Or is this even ok to do, if you spoke to Ludospherik for approval?

German:
https://truant.com/produkt/barbarians-of-lemuria-2

French:
http://www.ludospherik.fr/content/14-barbarians-of-lemuria

Unfortunately I have neither. I still have the old german edition and there are some minor differences, but this might just be because it's an old revision.

**Comment by LeRatierBretonnien** [comment]
As the illustration are the same, it means that the German version is a translation of the French version. So you must keep the reference to Ludospherik AND also mention the German editor.

**Comment by gsterling** [comment]
Shall I contact them or just add them to the translations?

**Comment by LeRatierBretonnien** [comment]
For faster exchange, contact me thru the Foundry Discord at LeRatierBretonnien#2065

**Comment by gsterling** [comment]
Sorry I don't have discord. I will send you the PR with a explanation and translation, so you know what exactly I added.

**Comment by LeRatierBretonnien** [comment]
OK. Ideally you should contact the German editor, saying that it is a free system, authorized by the French editor, and that the books are mandatory to play with.

**Comment by gsterling** [comment]
I will shoot them a message. I will wait with the PR for now, unless you already want to add it.

**Comment by LeRatierBretonnien** [comment]
You can go with the PR, I will add it.

**Comment by gsterling** [comment]
PR is here: https://github.com/ZigmundKreud/bol/pull/17

I sent Truant Spiele an e-mail and am waiting for their reply.

**Comment by LeRatierBretonnien** [comment]
OK, closed.
